version: "3.2"

services:
    vscode:
        build: .
        image: latexdevcontainer
        volumes:
            - ../:/workspace
            - /var/run/docker.sock:/var/run/docker.sock  # Docker socket.
            - ~/.ssh:/root/.ssh  # SSH keys.
            - ~/.zsh_history:/root/.zsh_history:z  # Shell history.
            - ~/.gitconfig:/root/.gitconfig  # Git config.
        environment:
            - TZ=
        entrypoint: ["zsh", "-c", "while sleep 1000; do :; done"]
